

  // adding config file for 64bit build. the config file 
  // was generated by running the configure script in the 
  // original python source package (2.7.0)
#ifdef __LP64__
#  include "pyconfig-64.h"
#else
#  include "pyconfig-32.h"
#endif
