
# Rules appended by makedepend

./posixmodule.o: $(srcdir)/./posixmodule.c; $(CC) $(PY_CFLAGS)  -c $(srcdir)/./posixmodule.c -o ./posixmodule.o
./posixmodule$(SO):  ./posixmodule.o; $(LDSHARED)  ./posixmodule.o   -o ./posixmodule$(SO)
./errnomodule.o: $(srcdir)/./errnomodule.c; $(CC) $(PY_CFLAGS)  -c $(srcdir)/./errnomodule.c -o ./errnomodule.o
./errnomodule$(SO):  ./errnomodule.o; $(LDSHARED)  ./errnomodule.o   -o ./errnomodule$(SO)
./pwdmodule.o: $(srcdir)/./pwdmodule.c; $(CC) $(PY_CFLAGS)  -c $(srcdir)/./pwdmodule.c -o ./pwdmodule.o
./pwdmodule$(SO):  ./pwdmodule.o; $(LDSHARED)  ./pwdmodule.o   -o ./pwdmodule$(SO)
./_sre.o: $(srcdir)/./_sre.c; $(CC) $(PY_CFLAGS)  -c $(srcdir)/./_sre.c -o ./_sre.o
./_sre$(SO):  ./_sre.o; $(LDSHARED)  ./_sre.o   -o ./_sre$(SO)
./_codecsmodule.o: $(srcdir)/./_codecsmodule.c; $(CC) $(PY_CFLAGS)  -c $(srcdir)/./_codecsmodule.c -o ./_codecsmodule.o
./_codecsmodule$(SO):  ./_codecsmodule.o; $(LDSHARED)  ./_codecsmodule.o   -o ./_codecsmodule$(SO)
./zipimport.o: $(srcdir)/./zipimport.c; $(CC) $(PY_CFLAGS)  -c $(srcdir)/./zipimport.c -o ./zipimport.o
./zipimport$(SO):  ./zipimport.o; $(LDSHARED)  ./zipimport.o   -o ./zipimport$(SO)
./symtablemodule.o: $(srcdir)/./symtablemodule.c; $(CC) $(PY_CFLAGS)  -c $(srcdir)/./symtablemodule.c -o ./symtablemodule.o
./_symtablemodule$(SO):  ./symtablemodule.o; $(LDSHARED)  ./symtablemodule.o   -o ./_symtablemodule$(SO)
./xxsubtype.o: $(srcdir)/./xxsubtype.c; $(CC) $(PY_CFLAGS)  -c $(srcdir)/./xxsubtype.c -o ./xxsubtype.o
./xxsubtype$(SO):  ./xxsubtype.o; $(LDSHARED)  ./xxsubtype.o   -o ./xxsubtype$(SO)
